import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-theme="pastel">
      <body
        className={`
          antialiased 
          flex flex-col items-center justify-center
          min-h-screen
          p-6 sm:p-10
        `}
      >
        {children}
      </body>
    </html>
  );
}
